included:
  - AsyncImageView
  - AsyncImageViewTests
  - Example
  - Package.swift

excluded:
  - .build
  - .swiftpm
  - Carthage
  - Example/Carthage
  - Example/Pods
  - Docs

opt_in_rules:
  - empty_count
  - explicit_init
  - overridden_super_call
  - redundant_nil_coalescing

analyzer_rules:
  - unused_import
  - unused_optional_binding

disabled_rules:
  - closure_parameter_position
  - comma
  - colon
  - control_statement
  - force_cast
  - function_body_length
  - function_name_whitespace
  - identifier_name
  - line_length
  - nesting
  - opening_brace
  - private_over_fileprivate
  - return_arrow_whitespace
  - todo
  - trailing_comma
  - trailing_newline
  - trailing_whitespace
  - type_body_length
  - unneeded_synthesized_initializer
  - vertical_parameter_alignment
  - vertical_whitespace
  - void_return
