git:
  submodules: false

language: objective-c
osx_image: xcode8.2
matrix:
  include:
    - os: osx
      before_install:
        - gem install scan
      script:
        - fastlane scan -s 'AsyncImageView-iOS' -a "iPhone SE (10.0)" -b "raw" -c -q "Release"

    - os: osx
      before_install:
        - gem install scan
      script:
        - fastlane scan -s 'AsyncImageView-iOS' -a "iPhone 6s (9.3)" -b "raw" -c -q "Release"

