git:
  submodules: false

language: objective-c
osx_image: xcode12
matrix:
  include:
    - os: osx
      before_install:
        - gem install scan
      script:
        - fastlane scan -s 'AsyncImageView-iOS' -a "iPhone 11" -b "raw" -c 

